-- EMPLOYEE REIMBURSEMENT MANAGEMENT SYSTEM


CREATE TABLE ERS_USER_ROLES(
	ERS_USER_ROLE_ID SERIAL PRIMARY KEY,
	USER_ROLE VARCHAR (10)
);
CREATE TABLE ERS_USERS(
	ERS_USERS_ID SERIAL PRIMARY KEY,
	ERS_USERNAME VARCHAR (50),
	ERS_PASSWORD VARCHAR (50),
	USER_FIRST_NAME VARCHAR (100),
	USER_LAST_NAME VARCHAR (100),
	USER_EMAIL VARCHAR (150),
	USER_ROLES_FK INT REFERENCES ERS_USER_ROLES (ERS_USER_ROLE_ID),
	UNIQUE (ERS_USERNAME, USER_EMAIL)
);
CREATE TABLE ERS_REIMBURSEMENT(
REIMB_ID SERIAL PRIMARY KEY,
REIMB_AMOUNT INT NOT NULL, 

);
CREATE TABLE ERS_REIMBURSEMENT_STATUS(
	REIMB_STATUS_ID SERIAL PRIMARY KEY,
	REIMB_STATUS VARCHAR(10)
);
CREATE TABLE ERS_REIMBURSEMENT_TYPE(
	REIMB_TYPE_ID SERIAL PRIMARY KEY,
	REIMB_TYPE VARCHAR (10)
);

